{{- if .Values.hpa }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fb-user-filestore-api-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fb-user-filestore-api-{{ .Values.environmentName }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{- end }}
